enable = true # 也是sub的默认值
env = "dev" # dev / fat / uat / pro

def_lang = "zh-Hans" # zh-Hans / zh / en

[log]
out_enable = false
out_level = 5 # 输出级别，0(fatal) 1(panic) 2(error) 3(warn) 4(info) 5(debug)
out_format = "06-01-02" # 可以按时间分割，06-01-02 15:04:05.000
file_check_interval = 60 # 检查间隔，min
file_max_age = 30  # 保留时间，day
file_max_size = 100  # 单文件最大大小，MB

[account]
enable = true

[client]
enable = true

[user]
enable = true