
[server]
api_domain = "user.katydid.com"
api_http_port = 80
api_https_port = 8080

[pgsql]
timeout = 10
timezone = "Asia/Shanghai"
ssl_mode = "app_disable"
max_retries = 5
retry_delay = 2

[pgsql.write]
host = "169.2.14.2"
port = 5432
db = "postgres"
user = "write"
pwd = "write_pwd"

[pgsql.read]
host = ["169.2.14.3"]
port = [5432]
db = ["postgres"]
user = ["read"]
pwd = ["read_pwd"]

[client.pgsql.write]
host = "169.2.14.1111"
port = 5432
db = "postgres"
user = "root"
pwd = "2ud8scsdc"
[client.pgsql.read]
host = ["169.2.14.1111", "169.2.14.2222"]
port = [5432]
db = ["postgres"]
user = ["root"]
pwd = ["2ud8scsdc"]

[redis]
address = "r-2zegwp14leh0qyqzrs.redis.rds.aliyuncs.com"
port = 6379
pwd = "LAOjiang1"
Host = ""
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200
