
[gateway]
enable = true
port = 30011
log_level = 1

[gateway.server]
http_domain = ""
http_port = "30011"
#http_port = 30012
log_level = 1

[pgsql]
timeout = 10
timezone = "Asia/Shanghai"
ssl_mode = "app_disable"