env_name = "环境_预上线"

[log]
con_levels = [] # 打印级别，1(fatal) 2(panic) 3(error) 4(warn) 5(info) 6(debug)
out_levels = [1,2,3,4,5,6] # 输出级别，1(fatal) 2(panic) 3(error) 4(warn) 5(info) 6(debug)

[lang]
defautl = "zh-CN" # zh-CN / en-US  必须是已有的语言

[auth]
enable = true

[client]
enable = true

[user]
enable = true
